# Generated by Django 3.0.6 on 2020-05-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200523_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo_post',
            field=models.TextField(blank=True, null=True, verbose_name='Conteudo'),
        ),
    ]
