# Generated by Django 3.0.6 on 2020-06-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao_curta', models.TextField(max_length=255)),
                ('descricao_lona', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto_imagem/%Y/%m/')),
                ('slug', models.SlugField(unique=True)),
                ('preco_marking', models.FloatField()),
                ('peco_marking_promocional', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('V', 'Variacao'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
    ]
