# Generated by Django 3.0.6 on 2020-06-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produo',
            new_name='Produto',
        ),
    ]
